import type { SkillGroup } from '@/types';

export const skills: SkillGroup[] = [
  {
    category: 'Programming & Analysis',
    skills: [
      'Python',
      'SQL',
      'Exploratory Data Analysis',
      'Data Cleaning',
      'Data Transformation',
      'Data Wrangling',
      'Statistical Analysis',
      'Feature Engineering',
      'Pandas',
      'NumPy',
    ],
  },
  {
    category: 'Business Intelligence',
    skills: [
      'Power BI',
      'DAX',
      'Power Query',
      'Data Modeling',
      'Dashboard Development',
      'Tableau',
      'Microsoft Excel',
      'Matplotlib',
      'Seaborn',
      'EDA',
      'Data Cleaning',
      'Statistics',
      'Pivot Tables',
      'XLOOKUP',
    ],
  },
  {
    category: 'Data Engineering',
    skills: [
      'Microsoft Fabric',
      'OneLake',
      'Lakehouse',
      'Warehouse',
      'Data Pipelines',
      'ETL Pipelines',
      'Data Integration',
    ],
  },
  {
    category: 'Engineering',
    skills: [
      'FastAPI',
      'REST APIs',
      'Star Schema',
      'Fact & Dimension Tables',
      'Joins',
      'CTEs',
      'Window Functions',
      'Aggregations',
      'Query Optimization',
      'PostgreSQL',
      'Git',
      'GitHub',
      'Streamlit',
      'Jira',
    ],
  },
];